spring:
  application:
    name: spring-boot-es-demo
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xh_college?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
